package ServiceLayer;

public enum Action {
    ILLEGAL_ACTION, DISPLAY_SCHEDULE, CHANGE_SCHEDULE, START_SHIFT, END_SHIFT, MID_SHIFT_ACTIONS, LOGOUT, REGISTER_EMPLOYEE,
    CERTIFY_EMPLOYEE, CREATE_SHIFT, VIEW_EMPLOYEE_DETAILS, EDIT_EMPLOYEE_DETAILS, DELETE_EMPLOYEE,
    VIEW_SHIFT, DELETE_SHIFT, MANAGE_DETAILS, GO_BACK ,EXIT_SYSTEM;
}
